name: 'PHP Coding standards validation'

on: pull_request

jobs:
  phpcs-checker:
    name: 'PHPCS Coding standards validation'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Install the drupal/coder(PHPCS)
        run: |
          sudo apk add jq
          VERSION=$(jq -r '.["packages"][] | select(.name == "drupal/coder") | .version' composer.lock)
          echo "Version the drupal/coder = $VERSION"
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          if [ -n "$VERSION" ]; then
            composer global require "drupal/coder:^$VERSION"
          else
            composer global require drupal/coder
          fi
      
      - name: Installing reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Configuring diff file
        run: |
          git config --global --add safe.directory .
          git diff --name-only -r origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF |\
          grep -E "web/(modules|themes|profiles)/custom" |\
          tr "\n" " " > /tmp/check
          grep -e 'php\|module\|inc\|install\|profile\|theme\|yml\|phpu' /tmp/check > /tmp/grep_checking || \
          if [ ! -s /tmp/grep_checking ]; then
            rm /tmp/grep_checking
            printf "PHPCS has nothing to check."
            exit 0
          fi
        
        - name: Run the phpcs
          run: |
            ~/.composer/vendor/bin/phpcs
            --extensions=css,inc,install,module,php,profile,test 
            --standard=Drupal,DrupalPractice 
            --report=checkstyle `cat /tmp/grep_checking` | 
            reviewdog
            -f="checkstyle" -name="PHPCS" 
            -reporter="github-pr-review" -fail-level=any 
            -filter-mode=nofilter -tee

