name: 'PHP Coding standards validation'

on: pull_request

jobs:
  phpcs-checker:
    name: 'PHPCS Coding standards validation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Install the drupal/coder(PHPCS)
        run: |
          sudo apt install jq
          VERSION=$(jq -r '.["packages"][] | select(.name == "drupal/coder") | .version' composer.lock)
          echo "Version the drupal/coder = $VERSION"
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          if [ -n "$VERSION" ]; then
            composer global require "drupal/coder:^$VERSION"
          else
            composer global require drupal/coder
          fi
      
      - name: Installing reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Configuring diff file
        run: |
          git config --global --add safe.directory .
          git diff --name-only -r origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF |\
          grep -E "web/(modules|themes|profiles)/custom" | \
          grep -E '\.php$|\.module$|\.inc$|\.install$|\.profile$|\.theme$|\.yml$|\.phpu$' > /tmp/grep|| true
          cat /tmp/grep
        
      - name: Run the phpcs
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ~/.composer/vendor/bin/phpcs \
          --extensions=css,inc,install,module,php,profile,test \
          --standard=Drupal,DrupalPractice \
          --report=checkstyle `cat /tmp/grep` | 
          reviewdog \
          -f="checkstyle" -name="PHPCS" \
          -reporter="github-pr-review" -fail-level=any \
          -filter-mode=nofilter -tee

